# Generated by Django 6.0.2 on 2026-02-28 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=50)),
                ('lon', models.DecimalField(decimal_places=5, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='city_name_idx'), models.Index(fields=['country_code'], name='city_country_code')],
                'constraints': [models.UniqueConstraint(fields=('lat', 'lon'), name='uniq_city_lat_lon')],
            },
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('temperature', models.IntegerField(max_length=150)),
                ('wind_speed', models.IntegerField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, max_length=100)),
                ('observed_at', models.DateTimeField(max_length=100)),
                ('humidity', models.IntegerField(max_length=100)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='weather.city')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('city', 'observed_at'), name='uniq_weather_snapshot_city_observed_at')],
            },
        ),
    ]
