# Generated by Django 6.0.2 on 2026-03-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
