# Generated by Django 6.0.2 on 2026-03-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_city_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathersnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weathersnapshot',
            name='humidity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weathersnapshot',
            name='observed_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weathersnapshot',
            name='temperature',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weathersnapshot',
            name='wind_speed',
            field=models.IntegerField(),
        ),
    ]
