# Generated by Django 6.0.2 on 2026-03-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='is_activ',
            new_name='is_active',
        ),
    ]
