# Generated by Django 6.0.2 on 2026-03-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_is_activ_subscription_is_active'),
        ('weather', '0003_alter_weathersnapshot_created_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('city', 'email'), name='uniq_city_email'),
        ),
    ]
